applications:
- name: rpozzi-jweb
  host: rpozzi-jweb
  domain: mybluemix.net
  path: rpozzi-liberty-config/liberty/servers/defaultServer
  instances: 1
  memory: 1024M
  disk_quota: 1024M
services:
- Auto-Scaling-31