DROP DATABASE "DB2INST1"."SAMPLE";

CREATE DATABASE "DB2INST1"."SAMPLE"

DROP SCHEMA "DB2INST1" RESTRICT;

CREATE SCHEMA "DB2INST1" AUTHORIZATION "SYSIBM";

--
-- Table structure for table `RESTAURANTS`
--
DROP TABLE "DB2INST1"."RESTAURANTS";
CREATE TABLE "DB2INST1"."RESTAURANTS" (
  "ID" INTEGER NOT NULL,
  "RESTNAME" VARCHAR(150) DEFAULT NULL
);
ALTER TABLE "DB2INST1"."RESTAURANTS" ADD CONSTRAINT "PK_RST" PRIMARY KEY("ID");
--
-- Dumping data for table `RESTAURANTS`
--
INSERT INTO "DB2INST1"."RESTAURANTS" (ID, RESTNAME) VALUES (1, 'I Fontanili');
INSERT INTO "DB2INST1"."RESTAURANTS" (ID, RESTNAME) VALUES (2, 'Il Ragazzo di Campagna');
INSERT INTO "DB2INST1"."RESTAURANTS" (ID, RESTNAME) VALUES (3, 'Hostaria del Porto');
INSERT INTO "DB2INST1"."RESTAURANTS" (ID, RESTNAME) VALUES (4, 'La Nautica');

--
-- Table structure for table `SEQUENCE`
--
DROP TABLE "DB2INST1"."SEQUENCE";
CREATE TABLE "DB2INST1"."SEQUENCE" (
  "SEQ_NAME" VARCHAR(50) NOT NULL,
  "SEQ_COUNT" DECIMAL(9,0) DEFAULT NULL
);
ALTER TABLE "DB2INST1"."SEQUENCE" ADD CONSTRAINT "PK_SEQ" PRIMARY KEY("SEQ_NAME");
--
-- Dumping data for table `SEQUENCE`
--
INSERT INTO "DB2INST1"."SEQUENCE" VALUES ('SEQ_GEN',4);

--
-- Table structure for table `TODOLIST`
--
DROP TABLE "DB2INST1"."TODOLIST";
CREATE TABLE "DB2INST1"."TODOLIST" (
  "L_ID" INTEGER NOT NULL,
  "C_NAME" VARCHAR(255) DEFAULT NULL
);
ALTER TABLE "DB2INST1"."TODOLIST" ADD CONSTRAINT "PK_TDL" PRIMARY KEY("L_ID");
--
-- Dumping data for table `TODOLIST`
--
INSERT INTO "DB2INST1"."TODOLIST" VALUES (1,'TODO');